services:
  - type: web
    name: savonnerie-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://meloulim:FOne5nKCrWURARsa@savon.8nq0q.mongodb.net/savon?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: savonnerie_jwt_secret_2024
      - key: FRONTEND_URL
        value: https://bucolic-mooncake-a9a162.netlify.app
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000